-- ============================================================
-- none-ls.lua  --  SOSTITUITO da formatting.lua
-- ============================================================
-- null-ls.nvim (jose-elias-alvarez) è stato abbandonato.
-- none-ls.nvim è il fork comunitario, ma non evolve più.
-- La configurazione di formattazione e linting è stata migrata a:
--
--   lua/plugins/formatting.lua
--     • stevearc/conform.nvim    →  formattazione async
--     • mfussenegger/nvim-lint   →  linting async
--     • mason-tool-installer     →  installa formatter/linter via Mason
--
-- Questo file è mantenuto vuoto per compatibilità.
-- ============================================================
return {}
